#!/bin/bash

# EC2 배포 가이드 스크립트
# 이 스크립트는 참고용입니다. 실제로는 EC2 터미널에서 실행하세요.

echo "=== EC2 배포 가이드 ==="
echo ""
echo "1. EC2 접속:"
echo "   ssh -i your-key.pem ubuntu@15.164.215.15"
echo ""
echo "2. Node.js 설치:"
echo "   curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -"
echo "   sudo apt-get install -y nodejs"
echo ""
echo "3. PM2 설치:"
echo "   sudo npm install -g pm2"
echo ""
echo "4. 프로젝트 클론:"
echo "   git clone https://github.com/jm4293/gganbu.git"
echo "   cd gganbu/server"
echo ""
echo "5. 의존성 설치:"
echo "   npm install"
echo ""
echo "6. 환경 변수 설정:"
echo "   cp .env.example .env"
echo "   nano .env"
echo ""
echo "7. PM2로 서버 시작:"
echo "   mkdir -p logs"
echo "   pm2 start ecosystem.config.js"
echo "   pm2 save"
echo "   pm2 startup"
echo ""
echo "8. 상태 확인:"
echo "   pm2 status"
echo "   pm2 logs gganbu-server"
echo ""
echo "=== WebSocket URL ==="
echo "http://15.164.215.15:3001"
echo ""
